### ISSUE TITLE
[Index]koto.cc的小问题

### ISSUE THREAD

**Issue by IcyBlue17** [kobe-koto/kobe-koto.github.io#1]
正常情况下网站中央有一大坨open.spotify.com 花了太长时间进行响应，建议换成网易云或者qq音乐，内地正常网络不用点方法访问不了spotify
另：作者海中学生吧qwq 我也是

**Comment by kobe-koto** [comment]
qwq
我頂喜歡spotify的qwq
實在不行的話我有空整個反代理加速，就是不知道能不能用（笑）
![image](https://user-images.githubusercontent.com/91669733/162090438-5c5792e9-a963-4539-bf23-8cfc6665ec9b.png)

**Comment by IcyBlue17** [comment]
az，我改了一下，改成国内哔哩哔哩源的nevergonnagiveyouup了XD，要是考虑到没反代改host之类的可以换成国内试一下
有个工具叫UsbeamHostsEditor，挺好用的，可以去试一下qwq
甚至他解决了我在网课摸鱼时无法连接到mc正版验证服务器的问题。。。

**Comment by IcyBlue17** [comment]
源寄掉了，换个源
[index.zip](https://github.com/kobe-koto/kobe-koto.github.io/files/8437353/index.zip)
8

**Comment by kobe-koto** [comment]
spotify proxy做好了
[`open-spotify-proxy.koto.workers.dev`](https://open-spotify-proxy.koto.workers.dev/)
指向open.spotify.com，由cloudflare支持

**Comment by IcyBlue17** [comment]
好了，完美
能压测koto.cc不awa

**Comment by kobe-koto** [comment]
。。。你在講什麽啊？
有自信把cf打掉嗎？
這就一靜態網站

**Comment by IcyBlue17** [comment]
支持的

**Comment by kobe-koto** [comment]
正確的
